version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  reviewers:
  - wherkamp
  assignees:
  - wherkamp
  ignore:
  - dependency-name: net.dv8tion:JDA
    versions:
    - ">= 4.a, < 4.1000000"
